spring.application.name=springboot-backend
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_system?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=ksjw79@GLA
spring.jpa.hibernate.ddl-auto = update